name: Lint and Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.14.0'
    - run: |
          (cd jumble && yarn install)
          (cd jumble && yarn run lint)
          (cd jumble && yarn run build)
